import { useEffect, useState } from "react";
import { collection, onSnapshot } from "firebase/firestore";
import { db } from "../../lib/firebase";
import { DIFFICULTIES } from "../creator/QuestsManager";

function useItems(collectionName) {
  const [items, setItems] = useState([]);
  useEffect(() => {
    return onSnapshot(collection(db, "worldData", collectionName, "items"), (snap) => {
      setItems(snap.docs.map((d) => ({ id: d.id, ...d.data() })));
    });
  }, [collectionName]);
  return items;
}

// The player-facing side of the "Mission" action (docs/TODO.md "Rumor and mission system"): unlike
// every other action in ActionBrowser, it needs a payload (missionId) before it can start - so
// ActionBrowser swaps its plain "Commencer" button for this list of the character's currently
// offered character.missionJournal entries (generated by the "Rumeur" action,
// functions/src/actions/rumeur.js), same convention as CraftingTab.jsx passing recetteId through
// to the "artisanat" handler.
export default function MissionPicker({ character, onStart, submitting, availabilityOk }) {
  const narrativeSubjects = useItems("narrativeSubjects");
  const adventureZones = useItems("adventureZones");
  const [selectedId, setSelectedId] = useState(null);

  const missions = character.missionJournal || [];

  // A mission resolved (or replaced by a fresh Rumeur roll) out from under the current selection
  // can't stay selected - same pattern as CraftingTab's own selectedId effect.
  useEffect(() => {
    if (selectedId && !missions.some((m) => m.id === selectedId)) setSelectedId(null);
  }, [missions, selectedId]);

  function missionLabel(mission) {
    const objective = narrativeSubjects.find((s) => s.id === mission.objectiveId);
    const difficultyLabel = DIFFICULTIES.find((d) => d.value === mission.difficulty)?.label || mission.difficulty;
    const zoneName = adventureZones.find((z) => z.id === mission.locationId)?.name;
    return `${objective?.nom || "Mission"} (${difficultyLabel})${zoneName ? ` — ${zoneName}` : ""}`;
  }

  return (
    <div className="mission-picker">
      {missions.length === 0 ? (
        <p className="empty-state">Aucune mission disponible — récoltez des rumeurs pour en générer.</p>
      ) : (
        <ul className="mission-list">
          {missions.map((mission) => (
            <li key={mission.id}>
              <button
                type="button"
                className={mission.id === selectedId ? "selected" : ""}
                onClick={() => setSelectedId(mission.id)}
              >
                {missionLabel(mission)}
              </button>
            </li>
          ))}
        </ul>
      )}

      <button
        type="button"
        disabled={!selectedId || submitting || !availabilityOk}
        onClick={() => onStart({ missionId: selectedId })}
      >
        Commencer
      </button>
    </div>
  );
}
