import { useEffect, useMemo, useState } from "react";
import { collection, onSnapshot } from "firebase/firestore";
import { db } from "../../lib/firebase";
import { DIFFICULTIES } from "../../lib/difficulties";

function useItems(collectionName) {
  const [items, setItems] = useState([]);
  useEffect(() => {
    return onSnapshot(collection(db, "worldData", collectionName, "items"), (snap) => {
      setItems(snap.docs.map((d) => ({ id: d.id, ...d.data() })));
    });
  }, [collectionName]);
  return items;
}

// The player-facing side of the "Mission" action (docs/TODO.md "Rumor and mission system"): unlike
// every other action in ActionBrowser, it needs a payload (missionId) before it can start - so
// ActionBrowser swaps its plain "Commencer" button for this list of the character's currently
// offered character.missionJournal entries (generated by the "Rumeur" action,
// functions/src/actions/rumeur.js), same convention as CraftingTab.jsx passing recetteId through
// to the "artisanat" handler.
export default function MissionPicker({ character, onStart, submitting, availabilityOk }) {
  const adventureZones = useItems("adventureZones");
  const regions = useItems("regions");
  const [selectedId, setSelectedId] = useState(null);

  const missions = character.missionJournal || [];

  // A mission resolved (or replaced by a fresh Rumeur roll) out from under the current selection
  // can't stay selected - same pattern as CraftingTab's own selectedId effect.
  useEffect(() => {
    if (selectedId && !missions.some((m) => m.id === selectedId)) setSelectedId(null);
  }, [missions, selectedId]);

  function missionLabel(mission) {
    const difficultyLabel = DIFFICULTIES.find((d) => d.value === mission.difficulty)?.label || mission.difficulty;
    const zoneName = adventureZones.find((z) => z.id === mission.locationId)?.name;
    return `${mission.name || "Mission"} (${difficultyLabel})${zoneName ? ` — ${zoneName}` : ""}`;
  }

  // Grouped by region first, then sorted by difficulty within each region (docs/TODO.md "Regional
  // mission generation and journal"'s "Mission journal UI" note), rather than the earlier flat list
  // - a character's missions now span several regions since generation is climate/region-aware.
  const groupedMissions = useMemo(() => {
    const byRegion = new Map();
    for (const mission of missions) {
      const key = mission.regionId || "";
      if (!byRegion.has(key)) byRegion.set(key, []);
      byRegion.get(key).push(mission);
    }

    const groups = [...byRegion.entries()].map(([regionId, regionMissions]) => ({
      regionId,
      regionName: regions.find((r) => r.id === regionId)?.name || "Région inconnue",
      missions: [...regionMissions].sort(
        (a, b) =>
          DIFFICULTIES.findIndex((d) => d.value === a.difficulty) -
          DIFFICULTIES.findIndex((d) => d.value === b.difficulty)
      ),
    }));

    groups.sort((a, b) => a.regionName.localeCompare(b.regionName));
    return groups;
  }, [missions, regions]);

  return (
    <div className="mission-picker">
      <fieldset className="action-loot-box">
        <legend>Missions en cours</legend>
        {missions.length === 0 ? (
          <p className="empty-state">Aucune mission disponible — récoltez des rumeurs pour en générer.</p>
        ) : (
          groupedMissions.map((group) => (
            <div key={group.regionId} className="mission-region-group">
              <h4>{group.regionName}</h4>
              <ul className="mission-list">
                {group.missions.map((mission) => (
                  <li key={mission.id}>
                    <button
                      type="button"
                      className={mission.id === selectedId ? "selected" : ""}
                      onClick={() => setSelectedId(mission.id)}
                    >
                      {missionLabel(mission)}
                    </button>
                  </li>
                ))}
              </ul>
            </div>
          ))
        )}
      </fieldset>

      <button
        type="button"
        disabled={!selectedId || submitting || !availabilityOk}
        onClick={() => onStart({ missionId: selectedId })}
      >
        Commencer
      </button>
    </div>
  );
}
